export const PROD_ENV = 'production'
export const DEV_ENV = 'development'

export const ROLE_ADMIN = 'Admin'
export const ROLE_SUPER_ADMIN = 'Super Admin'
export const ROLE_APP_USER = 'App User'

export const EDIT_PROFILE = 'Edit Profile'
export const MANAGE_PERMISSIONS = 'Manage Permissions'
export const MANAGE_ROLES = 'Manage Roles'
export const CREATE_USER = 'Create User'
export const EDIT_USER = 'Edit User'
export const DELETE_USER = 'Delete User'
export const LIST_USERS = 'List Users'
export const EDIT_ROLE_PERMISSIONS = 'Edit Role Permissions'
